name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # هر روز اجرا شود
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./output/github-contribution-grid-snake.svg
      - name: Commit & Push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generate contribution grid snake"
          add: "output/github-contribution-grid-snake.svg"